title: >
  Benjamin Chait
email: zeniths_gold.0c@icloud.com
description: >
  Personal site of Benjamin Chait.
# baseurl: "https://benjaminchait.net"
url: "https://benjaminchait.net"
twitter_username: benjaminchait
github_username: benjaminchait
# permalink: /:title/
timezone: America/Los_Angeles

# google_analytics:

plugins: [jekyll-redirect-from]

# assets:
#   sources:
#     - _assets/css
#     - _assets/images
#     - _assets/img(old)

pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true

include:
  - _redirects
